In [3]:
import numpy as np

In [22]:
a1=np.array([10,20,30,'abc'])
a2=np.array([40,50,60])
a1

array(['10', '20', '30', 'abc'], dtype='<U21')

In [11]:
a1+a2

array([50, 70, 90])

In [24]:
a1.dtype

dtype('<U21')

In [26]:
a1.itemsize

84

In [30]:
a1[0:4]

array(['10', '20', '30', 'abc'], dtype='<U21')

In [32]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
np.arange(3,99,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96])

In [63]:
arr=np.arange(2,101,2).reshape((10,5))
arr
# arr.ndim

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [61]:
np.linspace(1,8,11)

array([1. , 1.7, 2.4, 3.1, 3.8, 4.5, 5.2, 5.9, 6.6, 7.3, 8. ])

In [67]:
# arr.sum(axis=1)

In [69]:
# np.sqrt(arr)

In [77]:
# we want 46 op this is only work on 2d value, in 2nd line we want 78,80 
# arr[4,2]
# arr[7,3:5]
# arr>15


In [83]:
# for row in arr.ravel():
#     print(row)


In [6]:
np.vsplit(arr,2.5)
# np.hsplit(arr,2.5)

NameError: name 'np' is not defined

In [26]:
x='abcd'
x[::-1]


'dcba'